Repository mmf19144/programming2020, pull requests merged in 2020-11, with the labels that each got.

#26 1 Matrix
  Timur_Garipov/1 Matrix2.0.cpp
  Timur_Garipov/2 Wolves, rabbits.cpp
Labels: ineffective

#31 Add files via upload
  Александр Тарасенко/Matrix.cpp
Labels: changes-requested

#24 added matrix class with addition tast
  Sakrarov_Danil/1st_matrix_class/main.cpp
Labels: accepted
